<<<<<<< ours
#index:
#    path: /
#    controller: App\Controller\QuestionController::homepage
=======
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
>>>>>>> theirs
